id: P010615
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19374
  title: 'རྒྱལ་སྲས་ལག་ལེན་གྱི་ཟིན་བྲིས་སྨྲ་སེང་ཆོས་རྗེའི་ཞལ་ཁྲིད། '
  author: ''
  volumes:
    f1e0f75e6034444eba3ef87ca6e5d53c:
      image_group_id: I2PD19376
      title: ''
      volume_number: 1
      total_pages: 95
