id: P010615
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:16:37.100431
source_metadata:
  id: bdr:W2PD19374
  title: 'རྒྱལ་སྲས་ལག་ལེན་གྱི་ཟིན་བྲིས་སྨྲ་སེང་ཆོས་རྗེའི་ཞལ་ཁྲིད། '
  author: ''
  volumes:
    f1e0f75e6034444eba3ef87ca6e5d53c:
      image_group_id: I2PD19376
      title: ''
      volume_number: 1
      total_pages: 95
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
